### ISSUE TITLE
jasmine tests passing in the browser but not in the terminal

### ISSUE THREAD

**Issue by joshuabamboo** [learn-co-curriculum/js-apis-lab#8]
similar issue to https://github.com/learn-co-curriculum/js-ajax-callbacks-lab/issues/7 @PeterBell

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by michaelsimon** [comment]
i hit this and @joshuabamboo reviewed my code. my repo with my solution is https://github.com/michaelsimon/js-apis-lab-v-000.

**Comment by michaelsimon** [comment]
I was able to resolve this...
Issue was with my file_name key. When creating my JSON hash to send to create a gist I was trying to place it as a dynamic parameter like the following:

``` javascript
$.ajax({
 url: 'https://api.github.com/gists',
     type: 'POST',
     dataType: 'json',
     data: JSON.stringify({"description": description,
     "public": true,
     "files": {
       [file_name]: {
         "content": content
       }
     }
   }),
...
```

which worked in the browser but I guess the correct syntax is to initialize a new empty hash and set a key/value within that.

``` javascript
var files_hash = {};
files_hash[file_name] = { "content": content };
$.ajax({
    url: 'https://api.github.com/gists',
    type: 'POST',
    dataType: 'json',
    data: JSON.stringify({"description": description,
    "public": true,
    "files": files_hash
  }),
```

**Comment by pletcher** [comment]
@michaelsimon yeah, unfortunately the Jasmine tests use PhantomJS, which isn't caught up with the ES6 bits (like dynamic object keys).

I've been trying to migrate these labs over to a more up-to-date setup; should roll out at some point :)
