### ISSUE TITLE
Tests pass in the browser; fail in Terminal

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/js-apis-lab#9]
All tests pass via `learn -b` (Jasmine in the browser), and the application functions perfectly in the browser when I `python -m SimpleHTTPServer` to test it out.

All tests fail via `learn` (Jasmine in the Terminal) in the same manner as https://github.com/learn-co-curriculum/javascript-lazy-loader/issues/16 and https://github.com/learn-co-curriculum/js-jquery-prevent-default-lab/issues/5.

**Comment by gj** [comment]
I didn't want to open another issue for the same problem, but it happened again w/ the [Tweet Shortener lab](https://github.com/learn-co-curriculum/js-tweet-shortener) and the [JavaScript Final Project](https://github.com/learn-co-curriculum/js-github-final-project).

Since I've only seen a couple others w/ the same issue, I'm guessing it's some sort of Jasmine configuration quirk that happens to register in my decade-behind-the-times dev environment. I don't expect you'll have too many more students on OS X 10.7.5, so it's probably not worth the time to fix w/e is erroring out.

Lmk if you want me to close the three open issues, @AnnJohn

**Comment by gj** [comment]
Also, w/r/t [this response from pletcher](https://github.com/learn-co-curriculum/js-deli-counter/issues/8#issuecomment-219153723), I'm currently using learn-test v2.4.0

**Comment by gj** [comment]
@jd2rogers2 reports the same issue w/r/t the [JavaScript Final Project](https://github.com/learn-co-curriculum/js-github-final-project).

**Comment by bhollan** [comment]
I ran into this with another student tonight.  [Their code](https://github.com/bshap93/js-apis-lab-v-000) was using backticks for interpolation.  I substituted `'`s for the backticks and it worked with `learn -b` and `learn`.

CC: @aturkewi @gj

**Comment by aturkewi** [comment]
The issue here is using ES6 syntax. Our current test setup cannot handle it, that's why it was fixed when removing string interpolation. 
Added a note to the readme in PR #10 to not use ES6 syntax. Not worth updating the tests though as this lab will be deprecated when we merge in the mocha labs.
